[project]
name = "navari_frappehr_biostar"
authors = [
<<<<<<< HEAD
    { name = "Navari Limited", email = "mwendwa@navari.co.ke"}
]
description = "Frappe HR integration with Biostar Biometric"
=======
    { name = "navariltd", email = "mwendwa@navari.co.ke"}
]
description = "Biometrics Integration Application with FrappeHR"
>>>>>>> origin/develop
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
